version: 2

jobs:
  build:
    machine:
      node:
        version: 6.9.5
      npm:
        version: 3.10.10
    steps:
      - checkout
      - run: npm install -g npm@latest
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm run lint
      - run: npm test
  deploy:
    machine:
      node:
        version: 6.9.5
      npm:
        version: 3.10.10
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: npm publish

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /(?:^0|^[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)$/
